// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxtjs/stylelint-module" />
/// <reference types="@nuxtjs/style-resources" />
/// <reference types="@nuxtjs/fontawesome" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/pwa" />
/// <reference types="nuxt-i18n" />
/// <reference types="@storefront-ui/nuxt" />
/// <reference types="cookie-universal-nuxt" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
export {}
